### ISSUE TITLE
Items requesting never ends

### ISSUE THREAD

**Issue by dhilt** [Hill30/NGScroller#64]
If during data loading (and till it has been got) the scroller to be destroyed (i.e. by the transition to the other screen of the app or some other way) then data requesting will never stop till the eof/bof is reached.

The source of this issue is here: https://github.com/angular-ui/ui-utils/issues/356.

**Comment by jcstritt** [comment]
Hello, thanks for this incredible directive. But with v1.1.0 and when a tabbed page (with ui-scroll) is destroyed , an jqlite error is signaling (with jquery on, there is no problem) : 

    TypeError: Cannot read property 'length' of null
    at JQLite.(anonymous function) (http://localhost:8383/Psp-Compta/libs/angularjs-1.3.13/angular.js:3250:30)
    at Scope.$get.Scope.$broadcast (http://localhost:8383/Psp-Compta/libs/angularjs-1.3.13/angular.js:14720:28)
    at Scope.$get.Scope.$destroy (http://localhost:8383/Psp-Compta/libs/angularjs-1.3.13/angular.js:14340:14)
    at z (http://localhost:8383/Psp-Compta/libs/angularjs-1.3.13/angular-route.min.js:6:185)
    at http://localhost:8383/Psp-Compta/libs/angularjs-1.3.13/angular-route.min.js:6:456
    at publicLinkFn (http://localhost:8383/Psp-Compta/libs/angularjs-1.3.13/angular.js:6956:29)
    at $get.boundTranscludeFn (http://localhost:8383/Psp-Compta/libs/angularjs-1.3.13/angular.js:7096:16)
    at controllersBoundTransclude (http://localhost:8383/Psp-Compta/libs/angularjs-1.3.13/angular.js:7756:18)
    at x (http://localhost:8383/Psp-Compta/libs/angularjs-1.3.13/angular-route.min.js:6:364)
    at Scope.$get.Scope.$broadcast (http://localhost:8383/Psp-Compta/libs/angularjs-1.3.13/angular.js:14720:28)

**Comment by mfeingold** [comment]
Can you please post a repro?

**Comment by mfeingold** [comment]
@jcstritt : I think Denis nailed it down. Can you please confirm?

**Comment by dhilt** [comment]
[v1.1.1](https://github.com/Hill30/NGScroller/tree/v1.1.1) is available.
And [here](https://github.com/angular-ui/ui-utils/pull/373) is the fixing PR for ui.utils.

**Comment by jcstritt** [comment]
v1.1.1 tryed. No more error. Thank you @dhilt ! Have a good day.
